name: pub_api_client
description: An API Client for Pub to interact with public package information.
version: 2.3.0
homepage: https://github.com/leoafarias/pub_api_client

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  http: ^0.13.5

  oauth2: ^2.0.1
  path: ^1.8.2
  pubspec: ^2.3.0

dev_dependencies:
  build_runner: ^2.2.1
  build_version: ^2.1.1

  lints: ^2.0.1
  test: ^1.21.1
  test_cov: ^1.0.1
