name: Build Static API

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build-static:
    runs-on: ubuntu-latest

    container:
      image: dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
        # Grind task to build static files
      - name: Activate Grinder
        run: dart pub global activate grinder
      - name: Build static files
        run: dart pub run grinder
