# Do not run workflow for now
name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Install Cider
        run: pub global activate cider
      - name: Set new version
        run: pub global run cider version ${{ github.event.release.tag_name }}
      - name: Set a new release
        run: pub global run cider release
      - name: Build Runner
        run: pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        run: pub run test
      - name: Publish Dart/Flutter package
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: false
